// ─── Firearm Types ─────────────────────────────────────────────
export const FIREARM_TYPES = [
  "PISTOL",
  "RIFLE",
  "SHOTGUN",
  "SMG",
  "PCC",
  "REVOLVER",
  "BOLT_ACTION",
  "LEVER_ACTION",
] as const;

export type FirearmType = (typeof FIREARM_TYPES)[number];

export const FIREARM_TYPE_LABELS: Record<string, string> = {
  PISTOL: "Pistol",
  RIFLE: "Rifle",
  SHOTGUN: "Shotgun",
  SMG: "SMG",
  PCC: "PCC",
  REVOLVER: "Revolver",
  BOLT_ACTION: "Bolt Action",
  LEVER_ACTION: "Lever Action",
};

// ─── Slot Types ────────────────────────────────────────────────
export const SLOT_TYPES = [
  "MUZZLE",
  "BARREL",
  "BARREL_NUT",
  "HANDGUARD",
  "GAS_BLOCK",
  "GAS_TUBE",
  "BCG",
  "STOCK",
  "PISTOL_BRACE",
  "BUFFER_TUBE",
  "BUFFER",
  "BUFFER_SPRING",
  "GRIP",
  "OPTIC",
  "OPTIC_MOUNT",
  "UNDERBARREL",
  "MAGAZINE",
  "MAGWELL",
  "LIGHT",
  "LASER",
  "CHARGING_HANDLE",
  "LOWER_RECEIVER",
  "UPPER_RECEIVER",
  "LOWER_PARTS_KIT",
  "TRIGGER",
  "HAMMER",
  "DISCONNECTOR",
  "SAFETY_SELECTOR",
  "BOLT_CATCH",
  "MAGAZINE_CATCH",
  "TRIGGER_GUARD",
  "SLIDE",
  "FRAME",
  "SUPPRESSOR",
  "BIPOD",
  "SLING",
  "COMPENSATOR",
] as const;

export type SlotType = (typeof SLOT_TYPES)[number];

export const SLOT_TYPE_LABELS: Record<string, string> = {
  MUZZLE: "Muzzle",
  BARREL: "Barrel",
  BARREL_NUT: "Barrel Nut",
  HANDGUARD: "Handguard",
  GAS_BLOCK: "Gas Block",
  GAS_TUBE: "Gas Tube",
  BCG: "BCG",
  STOCK: "Stock",
  PISTOL_BRACE: "Pistol Brace",
  BUFFER_TUBE: "Buffer Tube",
  BUFFER: "Buffer",
  BUFFER_SPRING: "Buffer Spring",
  GRIP: "Grip",
  OPTIC: "Optic",
  OPTIC_MOUNT: "Optic Mount",
  UNDERBARREL: "Underbarrel",
  MAGAZINE: "Magazine",
  MAGWELL: "Magwell",
  LIGHT: "Light",
  LASER: "Laser",
  CHARGING_HANDLE: "Charging Handle",
  LOWER_RECEIVER: "Lower Receiver",
  UPPER_RECEIVER: "Upper Receiver",
  LOWER_PARTS_KIT: "Lower Parts Kit",
  TRIGGER: "Trigger",
  HAMMER: "Hammer",
  DISCONNECTOR: "Disconnector",
  SAFETY_SELECTOR: "Safety Selector",
  BOLT_CATCH: "Bolt Catch",
  MAGAZINE_CATCH: "Magazine Catch",
  TRIGGER_GUARD: "Trigger Guard",
  SLIDE: "Slide",
  FRAME: "Frame",
  SUPPRESSOR: "Suppressor",
  BIPOD: "Bipod",
  SLING: "Sling",
  COMPENSATOR: "Compensator",
};

// Which slots are available per firearm type
export const SLOTS_BY_FIREARM_TYPE: Record<FirearmType, SlotType[]> = {
  RIFLE: [
    "MUZZLE",
    "BARREL",
    "BARREL_NUT",
    "HANDGUARD",
    "GAS_BLOCK",
    "GAS_TUBE",
    "BCG",
    "STOCK",
    "PISTOL_BRACE",
    "BUFFER_TUBE",
    "BUFFER",
    "BUFFER_SPRING",
    "GRIP",
    "OPTIC",
    "OPTIC_MOUNT",
    "UNDERBARREL",
    "MAGAZINE",
    "MAGWELL",
    "LIGHT",
    "LASER",
    "CHARGING_HANDLE",
    "LOWER_RECEIVER",
    "UPPER_RECEIVER",
    "LOWER_PARTS_KIT",
    "TRIGGER",
    "HAMMER",
    "DISCONNECTOR",
    "SAFETY_SELECTOR",
    "BOLT_CATCH",
    "MAGAZINE_CATCH",
    "TRIGGER_GUARD",
    "SUPPRESSOR",
    "BIPOD",
    "SLING",
    "COMPENSATOR",
  ],
  PISTOL: [
    "MUZZLE",
    "BARREL",
    "SLIDE",
    "FRAME",
    "GRIP",
    "OPTIC",
    "OPTIC_MOUNT",
    "MAGAZINE",
    "MAGWELL",
    "LIGHT",
    "LASER",
    "TRIGGER",
    "SUPPRESSOR",
    "COMPENSATOR",
  ],
  SHOTGUN: [
    "MUZZLE",
    "BARREL",
    "STOCK",
    "GRIP",
    "OPTIC",
    "OPTIC_MOUNT",
    "UNDERBARREL",
    "MAGAZINE",
    "LIGHT",
    "LASER",
    "TRIGGER",
    "SLING",
    "COMPENSATOR",
  ],
  SMG: [
    "MUZZLE",
    "BARREL",
    "HANDGUARD",
    "GAS_BLOCK",
    "GAS_TUBE",
    "BCG",
    "STOCK",
    "BUFFER_TUBE",
    "BUFFER",
    "BUFFER_SPRING",
    "GRIP",
    "OPTIC",
    "OPTIC_MOUNT",
    "UNDERBARREL",
    "MAGAZINE",
    "MAGWELL",
    "LIGHT",
    "LASER",
    "CHARGING_HANDLE",
    "LOWER_PARTS_KIT",
    "TRIGGER",
    "HAMMER",
    "DISCONNECTOR",
    "SAFETY_SELECTOR",
    "BOLT_CATCH",
    "MAGAZINE_CATCH",
    "TRIGGER_GUARD",
    "SUPPRESSOR",
    "SLING",
    "COMPENSATOR",
  ],
  PCC: [
    "MUZZLE",
    "BARREL",
    "BARREL_NUT",
    "HANDGUARD",
    "GAS_BLOCK",
    "GAS_TUBE",
    "BCG",
    "STOCK",
    "PISTOL_BRACE",
    "BUFFER_TUBE",
    "BUFFER",
    "BUFFER_SPRING",
    "GRIP",
    "OPTIC",
    "OPTIC_MOUNT",
    "UNDERBARREL",
    "MAGAZINE",
    "MAGWELL",
    "LIGHT",
    "LASER",
    "CHARGING_HANDLE",
    "LOWER_PARTS_KIT",
    "TRIGGER",
    "HAMMER",
    "DISCONNECTOR",
    "SAFETY_SELECTOR",
    "BOLT_CATCH",
    "MAGAZINE_CATCH",
    "TRIGGER_GUARD",
    "SUPPRESSOR",
    "SLING",
    "COMPENSATOR",
  ],
  REVOLVER: [
    "BARREL",
    "GRIP",
    "OPTIC",
    "OPTIC_MOUNT",
    "TRIGGER",
    "COMPENSATOR",
  ],
  BOLT_ACTION: [
    "MUZZLE",
    "BARREL",
    "STOCK",
    "GRIP",
    "OPTIC",
    "OPTIC_MOUNT",
    "MAGAZINE",
    "TRIGGER",
    "BIPOD",
    "SLING",
    "SUPPRESSOR",
  ],
  LEVER_ACTION: [
    "MUZZLE",
    "BARREL",
    "STOCK",
    "GRIP",
    "OPTIC",
    "OPTIC_MOUNT",
    "TRIGGER",
    "SLING",
  ],
};

// ─── Build Statuses ────────────────────────────────────────────
export const BUILD_STATUSES = [
  { value: "in-progress", label: "In Progress" },
  { value: "complete", label: "Complete" },
  { value: "wishlist", label: "Wishlist" },
] as const;

export type BuildStatus = (typeof BUILD_STATUSES)[number]["value"];

// ─── Slot Categories (for grouping in build detail) ────────────
export const SLOT_CATEGORIES: { label: string; slots: string[] }[] = [
  {
    label: "Upper Assembly",
    slots: [
      "UPPER_RECEIVER",
      "BARREL",
      "HANDGUARD",
      "MUZZLE",
      "COMPENSATOR",
      "SUPPRESSOR",
      "CHARGING_HANDLE",
    ],
  },
  {
    label: "Lower Assembly",
    slots: ["LOWER_RECEIVER", "STOCK", "BUFFER_TUBE", "GRIP", "TRIGGER"],
  },
  { label: "Sighting", slots: ["OPTIC", "OPTIC_MOUNT"] },
  { label: "Magazine", slots: ["MAGAZINE"] },
  {
    label: "Attachments",
    slots: ["LIGHT", "LASER", "UNDERBARREL", "BIPOD", "SLING"],
  },
  { label: "Pistol Frame", slots: ["FRAME", "SLIDE"] },
];

// ─── Ammo Transaction Types ────────────────────────────────────
export const TRANSACTION_TYPES = [
  "PURCHASE",
  "RANGE_USE",
  "TRANSFER_OUT",
  "INVENTORY_CORRECTION",
  "EXPENDED",
] as const;

export type TransactionType = (typeof TRANSACTION_TYPES)[number];

export const TRANSACTION_TYPE_LABELS: Record<TransactionType, string> = {
  PURCHASE: "Purchase",
  RANGE_USE: "Range Use",
  TRANSFER_OUT: "Transfer Out",
  INVENTORY_CORRECTION: "Inventory Correction",
  EXPENDED: "Expended",
};

// ─── Type Badge Colors ────────────────────────────────────────
export const TYPE_BADGE_COLORS: Record<string, string> = {
  PISTOL: "border-[#00C2FF]/40 text-[#00C2FF]",
  RIFLE: "border-[#00C853]/40 text-[#00C853]",
  SHOTGUN: "border-[#F5A623]/40 text-[#F5A623]",
  SMG: "border-[#9C27B0]/40 text-[#CE93D8]",
  PCC: "border-[#00BCD4]/40 text-[#00BCD4]",
  REVOLVER: "border-[#E53935]/40 text-[#EF9A9A]",
  BOLT_ACTION: "border-[#8B9DB0]/40 text-vault-text-muted",
  LEVER_ACTION: "border-[#FF7043]/40 text-[#FF7043]",
};

// ─── Common Calibers ──────────────────────────────────────────
export const COMMON_CALIBERS = [
  "9mm Luger",
  ".45 ACP",
  ".40 S&W",
  ".380 ACP",
  "10mm Auto",
  ".357 Magnum",
  ".38 Special",
  ".44 Magnum",
  "5.56x45mm NATO",
  ".223 Remington",
  ".308 Winchester",
  "7.62x39mm",
  ".300 BLK",
  "6.5 Creedmoor",
  ".243 Winchester",
  ".30-06 Springfield",
  "12 Gauge",
  "20 Gauge",
  ".410 Bore",
  ".22 LR",
  ".17 HMR",
  ".22 WMR",
];

export const BULLET_TYPES = [
  "FMJ",
  "HP",
  "JHP",
  "OTM",
  "Frangible",
  "Tracer",
  "Subsonic",
  "Soft Point",
  "Match",
  "Other",
] as const;

export type BulletType = (typeof BULLET_TYPES)[number];
