// ─── Firearm Types ─────────────────────────────────────────────
export const FIREARM_TYPES = [
  "PISTOL",
  "RIFLE",
  "SHOTGUN",
  "SMG",
  "PCC",
  "REVOLVER",
  "BOLT_ACTION",
  "LEVER_ACTION",
] as const;

export type FirearmType = (typeof FIREARM_TYPES)[number];

export const FIREARM_TYPE_LABELS: Record<FirearmType, string> = {
  PISTOL: "Pistol",
  RIFLE: "Rifle",
  SHOTGUN: "Shotgun",
  SMG: "SMG",
  PCC: "PCC",
  REVOLVER: "Revolver",
  BOLT_ACTION: "Bolt Action",
  LEVER_ACTION: "Lever Action",
};

// ─── Slot Types ────────────────────────────────────────────────
export const SLOT_TYPES = [
  "MUZZLE",
  "BARREL",
  "HANDGUARD",
  "STOCK",
  "BUFFER_TUBE",
  "GRIP",
  "OPTIC",
  "OPTIC_MOUNT",
  "UNDERBARREL",
  "MAGAZINE",
  "LIGHT",
  "LASER",
  "CHARGING_HANDLE",
  "TRIGGER",
  "LOWER_RECEIVER",
  "UPPER_RECEIVER",
  "SLIDE",
  "FRAME",
  "SUPPRESSOR",
  "BIPOD",
  "SLING",
  "COMPENSATOR",
] as const;

export type SlotType = (typeof SLOT_TYPES)[number];

export const SLOT_TYPE_LABELS: Record<SlotType, string> = {
  MUZZLE: "Muzzle",
  BARREL: "Barrel",
  HANDGUARD: "Handguard",
  STOCK: "Stock",
  BUFFER_TUBE: "Buffer Tube",
  GRIP: "Grip",
  OPTIC: "Optic",
  OPTIC_MOUNT: "Optic Mount",
  UNDERBARREL: "Underbarrel",
  MAGAZINE: "Magazine",
  LIGHT: "Light",
  LASER: "Laser",
  CHARGING_HANDLE: "Charging Handle",
  TRIGGER: "Trigger",
  LOWER_RECEIVER: "Lower Receiver",
  UPPER_RECEIVER: "Upper Receiver",
  SLIDE: "Slide",
  FRAME: "Frame",
  SUPPRESSOR: "Suppressor",
  BIPOD: "Bipod",
  SLING: "Sling",
  COMPENSATOR: "Compensator",
};

// Which slots are available per firearm type
export const SLOTS_BY_FIREARM_TYPE: Record<FirearmType, SlotType[]> = {
  RIFLE: [
    "MUZZLE",
    "BARREL",
    "HANDGUARD",
    "STOCK",
    "BUFFER_TUBE",
    "GRIP",
    "OPTIC",
    "OPTIC_MOUNT",
    "UNDERBARREL",
    "MAGAZINE",
    "LIGHT",
    "LASER",
    "CHARGING_HANDLE",
    "TRIGGER",
    "LOWER_RECEIVER",
    "UPPER_RECEIVER",
    "SUPPRESSOR",
    "BIPOD",
    "SLING",
    "COMPENSATOR",
  ],
  PISTOL: [
    "MUZZLE",
    "BARREL",
    "SLIDE",
    "FRAME",
    "GRIP",
    "OPTIC",
    "OPTIC_MOUNT",
    "MAGAZINE",
    "LIGHT",
    "LASER",
    "TRIGGER",
    "SUPPRESSOR",
    "COMPENSATOR",
  ],
  SHOTGUN: [
    "MUZZLE",
    "BARREL",
    "STOCK",
    "GRIP",
    "OPTIC",
    "OPTIC_MOUNT",
    "UNDERBARREL",
    "MAGAZINE",
    "LIGHT",
    "LASER",
    "TRIGGER",
    "SLING",
    "COMPENSATOR",
  ],
  SMG: [
    "MUZZLE",
    "BARREL",
    "HANDGUARD",
    "STOCK",
    "GRIP",
    "OPTIC",
    "OPTIC_MOUNT",
    "UNDERBARREL",
    "MAGAZINE",
    "LIGHT",
    "LASER",
    "CHARGING_HANDLE",
    "TRIGGER",
    "SUPPRESSOR",
    "SLING",
    "COMPENSATOR",
  ],
  PCC: [
    "MUZZLE",
    "BARREL",
    "HANDGUARD",
    "STOCK",
    "BUFFER_TUBE",
    "GRIP",
    "OPTIC",
    "OPTIC_MOUNT",
    "UNDERBARREL",
    "MAGAZINE",
    "LIGHT",
    "LASER",
    "CHARGING_HANDLE",
    "TRIGGER",
    "SUPPRESSOR",
    "SLING",
    "COMPENSATOR",
  ],
  REVOLVER: [
    "BARREL",
    "GRIP",
    "OPTIC",
    "OPTIC_MOUNT",
    "TRIGGER",
    "COMPENSATOR",
  ],
  BOLT_ACTION: [
    "MUZZLE",
    "BARREL",
    "STOCK",
    "GRIP",
    "OPTIC",
    "OPTIC_MOUNT",
    "MAGAZINE",
    "TRIGGER",
    "BIPOD",
    "SLING",
    "SUPPRESSOR",
  ],
  LEVER_ACTION: [
    "MUZZLE",
    "BARREL",
    "STOCK",
    "GRIP",
    "OPTIC",
    "OPTIC_MOUNT",
    "TRIGGER",
    "SLING",
  ],
};

// ─── Ammo Transaction Types ────────────────────────────────────
export const TRANSACTION_TYPES = [
  "PURCHASE",
  "RANGE_USE",
  "TRANSFER_OUT",
  "INVENTORY_CORRECTION",
  "EXPENDED",
] as const;

export type TransactionType = (typeof TRANSACTION_TYPES)[number];

export const TRANSACTION_TYPE_LABELS: Record<TransactionType, string> = {
  PURCHASE: "Purchase",
  RANGE_USE: "Range Use",
  TRANSFER_OUT: "Transfer Out",
  INVENTORY_CORRECTION: "Inventory Correction",
  EXPENDED: "Expended",
};

// ─── Common Calibers ──────────────────────────────────────────
export const COMMON_CALIBERS = [
  "9mm Luger",
  ".45 ACP",
  ".40 S&W",
  ".380 ACP",
  "10mm Auto",
  ".357 Magnum",
  ".38 Special",
  ".44 Magnum",
  "5.56x45mm NATO",
  ".223 Remington",
  ".308 Winchester",
  "7.62x39mm",
  ".300 BLK",
  "6.5 Creedmoor",
  ".243 Winchester",
  ".30-06 Springfield",
  "12 Gauge",
  "20 Gauge",
  ".410 Bore",
  ".22 LR",
  ".17 HMR",
  ".22 WMR",
];

export const BULLET_TYPES = [
  "FMJ",
  "HP",
  "JHP",
  "OTM",
  "Frangible",
  "Tracer",
  "Subsonic",
  "Soft Point",
  "Match",
  "Other",
] as const;

export type BulletType = (typeof BULLET_TYPES)[number];
