@echo off
setlocal EnableDelayedExpansion

echo ╔══════════════════════════════════════════╗
echo ║      BlackVault — Setup Wizard           ║
echo ╚══════════════════════════════════════════╝
echo.

:: ── Prerequisites check ─────────────────────────────────────
docker compose version >nul 2>&1
if %errorlevel% neq 0 (
  docker-compose version >nul 2>&1
  if %errorlevel% neq 0 (
    echo ERROR: Docker with Compose is required.
    echo        Install Docker Desktop from https://www.docker.com/products/docker-desktop/
    pause
    exit /b 1
  )
  set COMPOSE=docker-compose
) else (
  set COMPOSE=docker compose
)

:: ── Existing installation guard ──────────────────────────────
if exist ".blackvault.env" (
  echo WARNING: .blackvault.env already exists.
  echo   Re-running install will generate NEW secret keys.
  echo   Any existing encrypted data will become unrecoverable.
  echo.
  set /p KEEP_EXISTING="  Keep existing config and just restart? [Y/n]: "
  if "!KEEP_EXISTING!"=="" set KEEP_EXISTING=Y
  if /i "!KEEP_EXISTING!"=="Y" (
    echo.
    echo Keeping existing config.
    echo Pulling latest BlackVault image...
    %COMPOSE% --env-file .blackvault.env pull
    echo.
    echo Starting BlackVault...
    %COMPOSE% --env-file .blackvault.env up -d
    echo.
    echo BlackVault started. Check logs with:
    echo   %COMPOSE% --env-file .blackvault.env logs -f
    echo.
    pause
    exit /b 0
  )
  echo.
)

:: ── Data directory ───────────────────────────────────────────
echo Where should BlackVault store its data?
echo   Default: %USERPROFILE%\.blackvault
set /p DATA_DIR_INPUT="  Data directory [press Enter for default]: "
if "%DATA_DIR_INPUT%"=="" (
  set DATA_DIR=%USERPROFILE%\.blackvault
) else (
  set DATA_DIR=%DATA_DIR_INPUT%
)

:: ── Port ─────────────────────────────────────────────────────
echo.
set /p PORT_INPUT="Port to run BlackVault on [3000]: "
if "%PORT_INPUT%"=="" set PORT=3000
if not "%PORT_INPUT%"=="" set PORT=%PORT_INPUT%

:: ── Secrets (minimal by default, optional advanced branch) ─────────────
echo.
set /p ADVANCED_SETUP="Advanced setup (provide your own secrets)? [y/N]: "

if /i "!ADVANCED_SETUP!"=="Y" (
  echo.
  echo Advanced setup selected. Leave blank to auto-generate.
  set /p VAULT_ENCRYPTION_KEY="  VAULT_ENCRYPTION_KEY [auto-generate if blank]: "
  set /p SESSION_SECRET="  SESSION_SECRET [auto-generate if blank]: "
)

if "!VAULT_ENCRYPTION_KEY!"=="" (
  for /f "delims=" %%k in ('powershell -NoProfile -Command "([System.BitConverter]::ToString([System.Security.Cryptography.RandomNumberGenerator]::GetBytes(32)) -replace '-','').ToLower()"') do (
    set VAULT_ENCRYPTION_KEY=%%k
  )
)

if "!SESSION_SECRET!"=="" (
  for /f "delims=" %%k in ('powershell -NoProfile -Command "([System.BitConverter]::ToString([System.Security.Cryptography.RandomNumberGenerator]::GetBytes(32)) -replace '-','').ToLower()"') do (
    set SESSION_SECRET=%%k
  )
)

if "!VAULT_ENCRYPTION_KEY!"=="" (
  echo ERROR: Failed to set VAULT_ENCRYPTION_KEY.
  echo        Use advanced setup to provide a manual value, or ensure PowerShell is available.
  pause
  exit /b 1
)

if "!SESSION_SECRET!"=="" (
  echo ERROR: Failed to set SESSION_SECRET.
  echo        Use advanced setup to provide a manual value, or ensure PowerShell is available.
  pause
  exit /b 1
)

:: ── Create directories ────────────────────────────────────────
echo.
echo Creating data directories...
if not exist "!DATA_DIR!\db" mkdir "!DATA_DIR!\db"
if not exist "!DATA_DIR!\uploads" mkdir "!DATA_DIR!\uploads"

:: ── Write .blackvault.env ─────────────────────────────────────
(
  echo # BlackVault configuration — generated by install.bat
  echo # CRITICAL: Keep this file safe.
  echo #   Losing VAULT_ENCRYPTION_KEY makes encrypted data unrecoverable.
  echo #   Losing SESSION_SECRET will invalidate active sessions.
  echo.
  echo DATA_DIR=!DATA_DIR!
  echo PORT=!PORT!
  echo VAULT_ENCRYPTION_KEY=!VAULT_ENCRYPTION_KEY!
  echo SESSION_SECRET=!SESSION_SECRET!
) > .blackvault.env

echo Configuration written to .blackvault.env

:: ── Pull and start ────────────────────────────────────────────
echo.
echo Pulling latest BlackVault image...
%COMPOSE% --env-file .blackvault.env pull

echo.
echo Starting BlackVault...
%COMPOSE% --env-file .blackvault.env up -d

echo.
echo Waiting for startup...
timeout /t 5 /nobreak >nul

:: ── Summary ───────────────────────────────────────────────────
echo.
echo ╔══════════════════════════════════════════════════════════╗
echo ║  BlackVault is ready!                                    ║
echo ╚══════════════════════════════════════════════════════════╝
echo.
echo   URL:         http://localhost:!PORT!
echo   Data stored: !DATA_DIR!
echo   Backup now:  .blackvault.env + !DATA_DIR!
echo.
echo   To stop BlackVault:
echo     %COMPOSE% --env-file .blackvault.env down
echo.
echo   To update BlackVault in the future, run:
echo     update.bat
echo.
pause
