@echo off
setlocal EnableDelayedExpansion

echo ╔══════════════════════════════════════════╗
echo ║      BlackVault — Setup Wizard           ║
echo ╚══════════════════════════════════════════╝
echo.

:: ── Prerequisites check ─────────────────────────────────────
docker compose version >nul 2>&1
if %errorlevel% neq 0 (
  docker-compose version >nul 2>&1
  if %errorlevel% neq 0 (
    echo ERROR: Docker with Compose is required.
    echo        Install Docker Desktop from https://www.docker.com/products/docker-desktop/
    pause
    exit /b 1
  )
  set COMPOSE=docker-compose
) else (
  set COMPOSE=docker compose
)

:: ── Data directory ───────────────────────────────────────────
echo Where should BlackVault store its data?
echo   Default: %USERPROFILE%\.blackvault
set /p DATA_DIR_INPUT="  Data directory [press Enter for default]: "
if "%DATA_DIR_INPUT%"=="" (
  set DATA_DIR=%USERPROFILE%\.blackvault
) else (
  set DATA_DIR=%DATA_DIR_INPUT%
)

:: ── Port ─────────────────────────────────────────────────────
echo.
set /p PORT_INPUT="Port to run BlackVault on [3000]: "
if "%PORT_INPUT%"=="" set PORT=3000
if not "%PORT_INPUT%"=="" set PORT=%PORT_INPUT%

:: ── Generate encryption key ───────────────────────────────────
echo.
echo Generating AES-256-GCM encryption key...
for /f "delims=" %%k in ('powershell -NoProfile -Command "([System.BitConverter]::ToString([System.Security.Cryptography.RandomNumberGenerator]::GetBytes(32)) -replace '-','').ToLower()"') do (
  set VAULT_ENCRYPTION_KEY=%%k
)

if "!VAULT_ENCRYPTION_KEY!"=="" (
  echo ERROR: Failed to generate encryption key. Ensure PowerShell is available.
  pause
  exit /b 1
)

:: ── Create directories ────────────────────────────────────────
echo.
echo Creating data directories...
if not exist "!DATA_DIR!\db" mkdir "!DATA_DIR!\db"
if not exist "!DATA_DIR!\uploads" mkdir "!DATA_DIR!\uploads"

:: ── Write .blackvault.env ─────────────────────────────────────
(
  echo # BlackVault configuration — generated by install.bat
  echo # CRITICAL: Keep this file safe. Losing VAULT_ENCRYPTION_KEY makes your data unrecoverable.
  echo.
  echo DATA_DIR=!DATA_DIR!
  echo PORT=!PORT!
  echo VAULT_ENCRYPTION_KEY=!VAULT_ENCRYPTION_KEY!
) > .blackvault.env

echo Configuration written to .blackvault.env

:: ── Build and start ───────────────────────────────────────────
echo.
echo Building BlackVault image (this may take a few minutes)...
%COMPOSE% --env-file .blackvault.env build

echo.
echo Starting BlackVault...
%COMPOSE% --env-file .blackvault.env up -d

echo.
echo Waiting for startup...
timeout /t 5 /nobreak >nul

:: ── Summary ───────────────────────────────────────────────────
echo.
echo ╔══════════════════════════════════════════════════════════╗
echo ║  BlackVault is ready!                                    ║
echo ╚══════════════════════════════════════════════════════════╝
echo.
echo   URL:         http://localhost:!PORT!
echo   Data stored: !DATA_DIR!
echo.
echo   WARNING: Back up your encryption key!
echo   If you lose it, your serial numbers and notes
echo   will be permanently unrecoverable.
echo.
echo   Key stored in: .blackvault.env
echo   Back up that file to a secure location now.
echo.
echo   To stop BlackVault:
echo     %COMPOSE% --env-file .blackvault.env down
echo.
echo   To update BlackVault in the future, run:
echo     update.bat
echo.
pause
