#!/bin/bash
set -e

echo "╔══════════════════════════════════════════╗"
echo "║      BlackVault — Setup Wizard           ║"
echo "╚══════════════════════════════════════════╝"
echo ""

# ── Pre-flight: Docker installed ─────────────────────────────
if ! command -v docker &>/dev/null; then
  echo "ERROR: Docker is not installed or not in your PATH."
  echo "       Install it from https://docs.docker.com/get-docker/ and re-run."
  exit 1
fi

# ── Pre-flight: Docker Compose available ─────────────────────
if ! docker compose version &>/dev/null 2>&1 && ! docker-compose version &>/dev/null 2>&1; then
  echo "ERROR: 'docker compose' (v2) or 'docker-compose' is required."
  echo "       Upgrade Docker Desktop or install the Compose plugin."
  exit 1
fi

# Prefer 'docker compose' (v2) over legacy 'docker-compose'
if docker compose version &>/dev/null 2>&1; then
  COMPOSE="docker compose"
else
  COMPOSE="docker-compose"
fi

generate_hex_secret() {
  if command -v openssl &>/dev/null; then
    openssl rand -hex 32
  elif command -v python3 &>/dev/null; then
    python3 -c "import secrets; print(secrets.token_hex(32))"
  else
    return 1
  fi
}

# ── Pre-flight: Docker daemon running ────────────────────────
if ! docker info > /dev/null 2>&1; then
  echo "ERROR: Docker Desktop is not running."
  echo "       Please open Docker Desktop and wait for it to start, then re-run this script."
  exit 1
fi

# ── Detect existing config ────────────────────────────────────
KEEP_EXISTING=false

if [ -f ".blackvault.env" ]; then
  echo "An existing .blackvault.env configuration was found."
  echo ""
  echo "  Press Enter  — keep existing settings and just rebuild/restart"
  echo "  Type 'new'   — start fresh with new settings"
  echo ""
  echo "  ⚠  WARNING: Choosing 'new' generates a new encryption key."
  echo "     Any existing encrypted data (serial numbers, notes) will be"
  echo "     unreadable with the new key unless you restore the old one."
  echo ""
  read -rp "  Your choice [Enter / new]: " CONFIG_CHOICE

  if [ -z "$CONFIG_CHOICE" ]; then
    KEEP_EXISTING=true
    echo ""
    echo "Keeping existing configuration."
    # Load values from existing env file for display in the summary
    DATA_DIR=$(grep '^DATA_DIR=' .blackvault.env | cut -d'=' -f2-)
    PORT=$(grep '^PORT=' .blackvault.env | cut -d'=' -f2-)
  else
    echo ""
    echo "Starting fresh. A new configuration and encryption key will be generated."
    KEEP_EXISTING=false
  fi
  echo ""
fi

# ── Gather settings (only if not keeping existing) ───────────
if [ "$KEEP_EXISTING" = false ]; then

  # Data directory
  DEFAULT_DATA="$HOME/.blackvault"
  echo "Where should BlackVault store its data?"
  echo "  This folder will contain your database and uploaded images."
  echo "  Default: $DEFAULT_DATA"
  read -rp "  Data directory [press Enter for default]: " DATA_DIR_INPUT
  DATA_DIR="${DATA_DIR_INPUT:-$DEFAULT_DATA}"
  DATA_DIR="${DATA_DIR%/}"   # strip trailing slash

  # Port — loop until a free port is chosen
  while true; do
    echo ""
    read -rp "Port to run BlackVault on [3000]: " PORT_INPUT
    PORT="${PORT_INPUT:-3000}"

    # Validate it looks like a number
    if ! [[ "$PORT" =~ ^[0-9]+$ ]]; then
      echo "  ERROR: '$PORT' is not a valid port number. Please enter a number."
      continue
    fi

    # Check if port is already in use
    if lsof -i :"$PORT" -sTCP:LISTEN -t &>/dev/null 2>&1; then
      echo ""
      echo "  ERROR: Port $PORT is already in use by another process."
      echo "         Please choose a different port."
    else
      break
    fi
  done

  # ── Password recovery secret option ───────────────────────────
  echo ""
  read -rp "Generate PASSWORD_RECOVERY_SECRET for account recovery workflows? [y/N]: " GENERATE_RECOVERY_SECRET
  GENERATE_RECOVERY_SECRET="${GENERATE_RECOVERY_SECRET:-N}"

  # Generate encryption key
  echo ""
  echo "Generating secrets..."
  VAULT_ENCRYPTION_KEY=$(generate_hex_secret) || {
    echo "ERROR: Unable to generate VAULT_ENCRYPTION_KEY."
    echo "       Install 'openssl' or 'python3', or use advanced setup with manual secrets."
    exit 1
  }

  SESSION_SECRET=$(generate_hex_secret) || {
    echo "ERROR: Unable to generate SESSION_SECRET."
    echo "       Install 'openssl' or 'python3'."
    exit 1
  }

  if [[ "$GENERATE_RECOVERY_SECRET" =~ ^[Yy]$ ]]; then
    PASSWORD_RECOVERY_SECRET=$(generate_hex_secret) || {
      echo "ERROR: Unable to generate PASSWORD_RECOVERY_SECRET."
      echo "       Install 'openssl' or 'python3'."
      exit 1
    }
  fi

  # Create data directories
  echo ""
  echo "Creating data directories..."
  mkdir -p "$DATA_DIR/db" "$DATA_DIR/uploads"

  # Verify the data directory is writable
  if [ ! -w "$DATA_DIR" ]; then
    echo "ERROR: Data directory '$DATA_DIR' is not writable."
    echo "       Check permissions or choose a different directory."
    exit 1
  fi

  # Write config file
  cat > .blackvault.env <<EOF
# BlackVault configuration — generated by install.sh
# CRITICAL: Keep this file safe and backed up.
#   Losing VAULT_ENCRYPTION_KEY makes all encrypted data permanently unrecoverable.
#   SESSION_SECRET is generated automatically on first container start and saved under DATA_DIR/db/config/session.env.
#   PASSWORD_RECOVERY_SECRET is optional but should be unique and never shared.

DATA_DIR=$DATA_DIR
PORT=$PORT
VAULT_ENCRYPTION_KEY=$VAULT_ENCRYPTION_KEY
SESSION_SECRET=$SESSION_SECRET
EOF

  chmod 600 .blackvault.env

  if [[ "$GENERATE_RECOVERY_SECRET" =~ ^[Yy]$ ]]; then
    echo "PASSWORD_RECOVERY_SECRET=$PASSWORD_RECOVERY_SECRET" >> .blackvault.env
    echo "Included PASSWORD_RECOVERY_SECRET in .blackvault.env"
  else
    echo "Skipped PASSWORD_RECOVERY_SECRET generation. You can add it later manually."
  fi

  echo "Configuration written to .blackvault.env"

else
  # Keeping existing config — still ensure data dirs exist
  echo "Ensuring data directories exist..."
  mkdir -p "$DATA_DIR/db" "$DATA_DIR/uploads"

  if [ ! -w "$DATA_DIR" ]; then
    echo "ERROR: Data directory '$DATA_DIR' is not writable."
    echo "       Check permissions on that directory."
    exit 1
  fi
fi

# ── [1/3] Build image ─────────────────────────────────────────
echo ""
echo "[1/3] Building BlackVault image (this takes 3-5 minutes on first run)..."
$COMPOSE --env-file .blackvault.env build

# ── [2/3] Start container ─────────────────────────────────────
echo ""
echo "[2/3] Starting BlackVault..."
$COMPOSE --env-file .blackvault.env up -d

# ── [3/3] Wait for healthy status (up to 90 s) ───────────────
echo ""
echo "[3/3] Waiting for BlackVault to start (up to 90 seconds)..."

_fail_with_logs() {
  local reason="$1"
  echo ""
  echo "╔══════════════════════════════════════════════════════════╗"
  echo "║  ERROR: $reason"
  echo "╚══════════════════════════════════════════════════════════╝"
  echo ""
  echo "Container logs:"
  echo "───────────────────────────────────────────────────────────"
  $COMPOSE --env-file .blackvault.env logs --tail=60
  echo "───────────────────────────────────────────────────────────"
  echo ""
  echo "  Common causes:"
  echo "    - Database migration failed (search logs above for 'Error')"
  echo "    - Port $PORT already in use by another process"
  echo "    - Insufficient disk space or permissions in $DATA_DIR"
  echo ""
  echo "  To clean up and retry:"
  echo "    $COMPOSE --env-file .blackvault.env down"
  echo "    ./install.sh"
  exit 1
}

ATTEMPTS=0
MAX_ATTEMPTS=45   # 45 × 2 s = 90 s

while true; do
  PS_OUT=$($COMPOSE --env-file .blackvault.env ps 2>/dev/null)

  if echo "$PS_OUT" | grep -q "(healthy)"; then
    echo ""
    echo "BlackVault is healthy."
    break
  fi

  # Fail fast on crash-loop or clean exit with error
  if echo "$PS_OUT" | grep -qE "Restarting|Exit [^0]|exited \([^0]\)"; then
    _fail_with_logs "BlackVault failed to start (crash loop detected)"
  fi

  ATTEMPTS=$((ATTEMPTS + 1))
  if [ "$ATTEMPTS" -ge "$MAX_ATTEMPTS" ]; then
    _fail_with_logs "BlackVault did not become healthy within 90 seconds"
  fi

  printf "."
  sleep 2
done

# ── Summary ───────────────────────────────────────────────────
echo ""
echo "╔══════════════════════════════════════════════════════════╗"
echo "║  BlackVault is ready!                                    ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""
echo "  URL:         http://localhost:$PORT"
echo ""
echo "  To access from your phone on the same Wi-Fi:"
echo "    Find your local IP with:"
echo "      Mac:     ipconfig getifaddr en0"
echo "      Windows: ipconfig"
echo "    Then open: http://<your-ip>:$PORT"
echo ""
echo "  Data stored: $DATA_DIR"
echo ""
echo "  WARNING: Back up your encryption key!"
echo "  If you lose it, your serial numbers and notes"
echo "  will be permanently unrecoverable."
echo ""
echo "  Key stored in: .blackvault.env"
echo "  Back up that file to a secure location now."
echo ""
echo "  Session secret is auto-managed at runtime in:"
echo "    $DATA_DIR/db/config/session.env"
echo "  Deleting that file forces a new secret and logs out all sessions."
echo ""
echo "  To stop BlackVault:"
echo "    $COMPOSE --env-file .blackvault.env down"
echo ""
echo "  To update BlackVault in the future, run:"
echo "    ./update.sh"
echo ""
