#!/bin/bash
set -euo pipefail

echo "╔══════════════════════════════════════════╗"
echo "║   ProjectBlackVault Setup Wizard         ║"
echo "╚══════════════════════════════════════════╝"
echo ""

if ! command -v docker >/dev/null 2>&1; then
  echo "ERROR: Docker is not installed or not in your PATH."
  echo "Install Docker Desktop, then run this script again."
  echo "Download: https://docs.docker.com/get-docker/"
  exit 1
fi

if docker compose version >/dev/null 2>&1; then
  COMPOSE="docker compose"
elif docker-compose version >/dev/null 2>&1; then
  COMPOSE="docker-compose"
else
  echo "ERROR: Docker Compose is not available."
  echo "Install or update Docker Desktop, then retry."
  exit 1
fi

health_check() {
  local url="$1"
  if command -v curl >/dev/null 2>&1; then
    curl -fsS "$url" 2>/dev/null | grep -q '"status":"ok"'
    return $?
  fi
  if command -v wget >/dev/null 2>&1; then
    wget -qO- "$url" 2>/dev/null | grep -q '"status":"ok"'
    return $?
  fi
  return 1
}

wait_for_health() {
  local port="$1"
  local retries=45
  local url="http://localhost:${port}/api/health"

  echo "Waiting for ProjectBlackVault to become ready..."
  for i in $(seq 1 "$retries"); do
    if health_check "$url"; then
      echo "ProjectBlackVault is ready."
      return 0
    fi
    sleep 2
  done

  echo "ProjectBlackVault is still starting."
  echo "Check logs with:"
  echo "  $COMPOSE --env-file .blackvault.env logs -f"
  return 1
}

if [ -f ".blackvault.env" ]; then
  echo "Existing .blackvault.env found."
  echo "Re-running install can rotate your encryption key and lock you out of encrypted fields."
  echo ""
  read -rp "Keep existing config and only restart the app? [Y/n]: " KEEP_EXISTING
  KEEP_EXISTING="${KEEP_EXISTING:-Y}"
  if [[ "$KEEP_EXISTING" =~ ^[Yy]$ ]]; then
    # shellcheck disable=SC1091
    source .blackvault.env 2>/dev/null || true
    PORT="${PORT:-3000}"

    echo "Trying to pull latest image (safe to skip if this is a local source build)..."
    if ! $COMPOSE --env-file .blackvault.env pull; then
      echo "Image pull skipped or failed; continuing with local build."
    fi

    echo "Starting ProjectBlackVault..."
    $COMPOSE --env-file .blackvault.env up -d --build --remove-orphans
    wait_for_health "$PORT" || true
    echo ""
    echo "Open: http://localhost:${PORT}"
    exit 0
  fi
  echo ""
fi

DEFAULT_DATA="$HOME/.projectblackvault"
echo "Where should ProjectBlackVault store your data?"
echo "This folder stores your vault database and uploaded files."
echo "Default: $DEFAULT_DATA"
read -rp "Data directory [press Enter for default]: " DATA_DIR_INPUT
DATA_DIR="${DATA_DIR_INPUT:-$DEFAULT_DATA}"
DATA_DIR="${DATA_DIR%/}"

echo ""
read -rp "Port to run ProjectBlackVault on [3000]: " PORT_INPUT
PORT="${PORT_INPUT:-3000}"
if ! [[ "$PORT" =~ ^[0-9]+$ ]] || [ "$PORT" -lt 1 ] || [ "$PORT" -gt 65535 ]; then
  echo "ERROR: Port must be a number between 1 and 65535."
  exit 1
fi

echo ""
read -rp "Allow access from other devices on your local network (phone/tablet)? [y/N]: " LAN_ACCESS
LAN_ACCESS="${LAN_ACCESS:-N}"
if [[ "$LAN_ACCESS" =~ ^[Yy]$ ]]; then
  BIND_ADDRESS="0.0.0.0"
else
  BIND_ADDRESS="127.0.0.1"
fi

echo ""
echo "Generating encryption key..."
if command -v openssl >/dev/null 2>&1; then
  VAULT_ENCRYPTION_KEY="$(openssl rand -hex 32)"
elif command -v python3 >/dev/null 2>&1; then
  VAULT_ENCRYPTION_KEY="$(python3 -c "import secrets; print(secrets.token_hex(32))")"
else
  echo "ERROR: Could not generate an encryption key."
  echo "Install openssl or python3, then run install.sh again."
  exit 1
fi

echo ""
echo "Creating data directories..."
mkdir -p "$DATA_DIR/db" "$DATA_DIR/uploads"
chmod 700 "$DATA_DIR" "$DATA_DIR/db" "$DATA_DIR/uploads" 2>/dev/null || true

cat > .blackvault.env <<EOF
# ProjectBlackVault configuration — generated by install.sh
# Keep this file safe. It includes your encryption key.

DATA_DIR=$DATA_DIR
PORT=$PORT
BIND_ADDRESS=$BIND_ADDRESS
SESSION_COOKIE_SECURE=auto
ALLOW_ENCRYPTION_KEY_EXPORT=false
VAULT_ENCRYPTION_KEY=$VAULT_ENCRYPTION_KEY
EOF

chmod 600 .blackvault.env 2>/dev/null || true

echo "Wrote configuration to .blackvault.env"

echo ""
echo "Trying to pull latest image (safe to skip if this is a local source build)..."
if ! $COMPOSE --env-file .blackvault.env pull; then
  echo "Image pull skipped or failed; continuing with local build."
fi

echo ""
echo "Starting ProjectBlackVault..."
$COMPOSE --env-file .blackvault.env up -d --build --remove-orphans
wait_for_health "$PORT" || true

echo ""
echo "╔══════════════════════════════════════════════════════════╗"
echo "║             ProjectBlackVault is ready                  ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""
echo "Open on this computer: http://localhost:$PORT"
if [ "$BIND_ADDRESS" = "0.0.0.0" ]; then
  echo "Local-network access is enabled."
else
  echo "Local-network access is disabled (safer default)."
fi
echo "Data folder: $DATA_DIR"
echo ""
echo "IMPORTANT: Back up .blackvault.env in a secure location."
echo "If you lose VAULT_ENCRYPTION_KEY, encrypted fields cannot be recovered."
echo "SESSION_SECRET is auto-managed in your data folder by the container."
echo ""
echo "To stop:"
echo "  $COMPOSE --env-file .blackvault.env down"
echo "To update:"
echo "  ./update.sh"
