#!/bin/bash
set -e

echo "╔══════════════════════════════════════════╗"
echo "║      BlackVault — Setup Wizard           ║"
echo "╚══════════════════════════════════════════╝"
echo ""

# ── Prerequisites check ─────────────────────────────────────
if ! command -v docker &>/dev/null; then
  echo "ERROR: Docker is not installed or not in your PATH."
  echo "       Install it from https://docs.docker.com/get-docker/ and re-run."
  exit 1
fi

if ! docker compose version &>/dev/null 2>&1 && ! docker-compose version &>/dev/null 2>&1; then
  echo "ERROR: 'docker compose' (v2) or 'docker-compose' is required."
  echo "       Upgrade Docker Desktop or install the Compose plugin."
  exit 1
fi

# Prefer 'docker compose' (v2) over legacy 'docker-compose'
if docker compose version &>/dev/null 2>&1; then
  COMPOSE="docker compose"
else
  COMPOSE="docker-compose"
fi

generate_hex_secret() {
  if command -v openssl &>/dev/null; then
    openssl rand -hex 32
  elif command -v python3 &>/dev/null; then
    python3 -c "import secrets; print(secrets.token_hex(32))"
  else
    return 1
  fi
}

# ── Existing installation guard ──────────────────────────────
if [ -f ".blackvault.env" ]; then
  echo "WARNING: .blackvault.env already exists."
  echo "  Re-running install will generate a NEW encryption key."
  echo "  Any existing encrypted data will become unrecoverable."
  echo "  SESSION_SECRET stays in the data directory unless you reset it manually."
  echo ""
  read -rp "  Keep existing config and just restart? [Y/n]: " KEEP_EXISTING
  KEEP_EXISTING="${KEEP_EXISTING:-Y}"
  if [[ "$KEEP_EXISTING" =~ ^[Yy]$ ]]; then
    echo ""
    echo "Keeping existing config."
    # shellcheck disable=SC1091
    source .blackvault.env 2>/dev/null || true
    echo "Pulling latest BlackVault image..."
    $COMPOSE --env-file .blackvault.env pull
    echo ""
    echo "Starting BlackVault..."
    $COMPOSE --env-file .blackvault.env up -d
    echo ""
    echo "Waiting for BlackVault to be ready..."
    MAX_RETRIES=15
    for i in $(seq 1 $MAX_RETRIES); do
      if wget -qO- "http://localhost:${PORT:-3000}/api/health" 2>/dev/null | grep -q '"ok"'; then
        echo "BlackVault is ready."
        break
      fi
      if [ "$i" -eq "$MAX_RETRIES" ]; then
        echo "Still starting — check logs with:"
        echo "  $COMPOSE --env-file .blackvault.env logs -f"
      else
        sleep 2
      fi
    done
    echo ""
    echo "  URL: http://localhost:${PORT:-3000}"
    echo ""
    exit 0
  fi
  echo ""
fi

# ── Data directory ───────────────────────────────────────────
DEFAULT_DATA="$HOME/.blackvault"
echo "Where should BlackVault store its data?"
echo "  This folder will contain your database and uploaded images."
echo "  Default: $DEFAULT_DATA"
read -rp "  Data directory [press Enter for default]: " DATA_DIR_INPUT
DATA_DIR="${DATA_DIR_INPUT:-$DEFAULT_DATA}"
DATA_DIR="${DATA_DIR%/}"   # strip trailing slash

# ── Port ─────────────────────────────────────────────────────
echo ""
read -rp "Port to run BlackVault on [3000]: " PORT_INPUT
PORT="${PORT_INPUT:-3000}"

# ── Password recovery secret option ───────────────────────────
echo ""
read -rp "Generate PASSWORD_RECOVERY_SECRET for account recovery workflows? [y/N]: " GENERATE_RECOVERY_SECRET
GENERATE_RECOVERY_SECRET="${GENERATE_RECOVERY_SECRET:-N}"

# ── Secrets (minimal by default, optional advanced branch) ───
echo ""
read -rp "Advanced setup (provide your own secrets)? [y/N]: " ADVANCED_SETUP

if [[ "$ADVANCED_SETUP" =~ ^[Yy]$ ]]; then
  echo ""
  echo "Advanced setup selected. Leave blank to auto-generate."
  read -rp "  VAULT_ENCRYPTION_KEY [auto-generate if blank]: " VAULT_ENCRYPTION_KEY
fi

if [ -z "${VAULT_ENCRYPTION_KEY:-}" ]; then
  VAULT_ENCRYPTION_KEY=$(generate_hex_secret) || {
    echo "ERROR: Unable to generate VAULT_ENCRYPTION_KEY."
    echo "       Install 'openssl' or 'python3', or use advanced setup with manual secrets."
    exit 1
  }
fi

if [[ "$GENERATE_RECOVERY_SECRET" =~ ^[Yy]$ ]]; then
  PASSWORD_RECOVERY_SECRET=$(generate_hex_secret) || {
    echo "ERROR: Unable to generate PASSWORD_RECOVERY_SECRET."
    echo "       Install 'openssl' or 'python3'."
    exit 1
  }
fi

# ── Create directories ────────────────────────────────────────
echo ""
echo "Creating data directories..."
mkdir -p "$DATA_DIR/db" "$DATA_DIR/uploads"

# ── Write .blackvault.env ─────────────────────────────────────
cat > .blackvault.env <<EOF
# BlackVault configuration — generated by install.sh
# CRITICAL: Keep this file safe and backed up.
#   Losing VAULT_ENCRYPTION_KEY makes all encrypted data permanently unrecoverable.
#   SESSION_SECRET is generated automatically on first container start and saved under DATA_DIR/db/config/session.env.
#   PASSWORD_RECOVERY_SECRET is optional but should be unique and never shared.

DATA_DIR=$DATA_DIR
PORT=$PORT
VAULT_ENCRYPTION_KEY=$VAULT_ENCRYPTION_KEY
EOF

if [[ "$GENERATE_RECOVERY_SECRET" =~ ^[Yy]$ ]]; then
  echo "PASSWORD_RECOVERY_SECRET=$PASSWORD_RECOVERY_SECRET" >> .blackvault.env
  echo "Included PASSWORD_RECOVERY_SECRET in .blackvault.env"
else
  echo "Skipped PASSWORD_RECOVERY_SECRET generation. You can add it later manually."
fi

echo "Configuration written to .blackvault.env"

# ── Pull and start ────────────────────────────────────────────
echo ""
echo "Pulling latest BlackVault image..."
$COMPOSE --env-file .blackvault.env pull

echo ""
echo "Starting BlackVault..."
$COMPOSE --env-file .blackvault.env up -d

echo ""
echo "Waiting for BlackVault to be ready..."
MAX_RETRIES=15
for i in $(seq 1 $MAX_RETRIES); do
  if wget -qO- "http://localhost:${PORT}/api/health" 2>/dev/null | grep -q '"ok"'; then
    echo "BlackVault is ready."
    break
  fi
  if [ "$i" -eq "$MAX_RETRIES" ]; then
    echo "Still starting — check logs with:"
    echo "  $COMPOSE --env-file .blackvault.env logs -f"
  else
    sleep 2
  fi
done

# ── Summary ───────────────────────────────────────────────────
echo ""
echo "╔══════════════════════════════════════════════════════════╗"
echo "║  BlackVault is ready!                                    ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""
echo "  URL:         http://localhost:$PORT"
echo "  Data stored: $DATA_DIR"
echo ""
echo "  WARNING: Back up your encryption key!"
echo "  If you lose it, your serial numbers and notes"
echo "  will be permanently unrecoverable."
echo ""
echo "  Key stored in: .blackvault.env"
echo "  Back up that file to a secure location now."
echo ""
echo "  Session secret is auto-managed at runtime in:"
echo "    $DATA_DIR/db/config/session.env"
echo "  Deleting that file forces a new secret and logs out all sessions."
echo ""
echo "  To stop BlackVault:"
echo "    $COMPOSE --env-file .blackvault.env down"
echo ""
echo "  To update BlackVault in the future, run:"
echo "    ./update.sh"
echo ""
