var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/builds/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__2bbd1c3d._.js")
R.c("server/chunks/ssr/_10800943._.js")
R.c("server/chunks/ssr/src_lib_prisma_ts_59f4251a._.js")
R.c("server/chunks/ssr/_0efddc1b._.js")
R.c("server/chunks/ssr/[root-of-the-server]__c6930fe4._.js")
R.c("server/chunks/ssr/[root-of-the-server]__85eeb158._.js")
R.c("server/chunks/ssr/node_modules_next_dist_70ed294b._.js")
R.c("server/chunks/ssr/src_app_5b2047f8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__0fdb203b._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_builds_page_actions_17770f45.js")
R.m(48399)
module.exports=R.m(48399).exports
